import Navbar from "@/components/navbar/Navbar";
import StoreProvider from "@/provider/StoreProvider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Life Saving Blood Donation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar>{children}</Navbar>
        </StoreProvider>
      </body>
    </html>
  );
}
