import logo from "@/assets/Logo.svg";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Life Saving Blood Donation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const navItems = (
    <>
      <li>
        <Link href="/">Home</Link>
      </li>
      <li>
        <Link href="/about">About</Link>
      </li>
      <li>
        <Link href="/findBlood">Find Blood</Link>
      </li>

      <Link href="/login">
        <li className="w-[247px] btn btn-neutral btn-outline">Login</li>
      </Link>
    </>
  );
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className="drawer">
          <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col">
            {/* Navbar */}
            <nav className="w-full navbar max-w-7xl mx-auto sticky top-0">
              <div className="flex-1">
                <div className="w-16 lg:w-20">
                  <Image src={logo} alt="logo" />
                </div>
              </div>
              <div className="flex-none lg:hidden">
                <label
                  htmlFor="my-drawer-3"
                  aria-label="open sidebar"
                  className="btn btn-square btn-ghost"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    className="inline-block w-6 h-6 stroke-current"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h16M4 18h16"
                    ></path>
                  </svg>
                </label>
              </div>
              <div className="flex-none hidden lg:block">
                <ul className="menu menu-horizontal">
                  {/* Navbar menu content here */}
                  {navItems}
                </ul>
              </div>
            </nav>
            {/* Page content here */}
            {children}
          </div>

          <div className="drawer-side">
            <label
              htmlFor="my-drawer-3"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu p-4 w-80 min-h-full bg-base-200">
              {/* Sidebar content here */}
              {navItems}
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
